services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monappdb
    ports:
      - "5441:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
